In [2]:
import pandas as pd
df = pd.read_excel(r'data.xlsx')

In [3]:
df

   A   B
0  a  50
1  c  20
2  d   1
3  a  20
4  c   4
5  d  78
6  d  36
7  c  44

In [5]:
df['c'] = df['A']

In [6]:
df.head()

   A   B  c
0  a  50  a
1  c  20  c
2  d   1  d
3  a  20  a
4  c   4  c